services:
  mongo4:
    container_name: mongo4
    image: mongo
    volumes:
      - ./data:/data/proyecto
      - ./rs-init.sh:/scripts/rs-init.sh
      - ./init.js:/scripts/init.js
    networks:
      - mongo-network
    ports:
      - 27020:27017
    depends_on:
      - mongo5
      - mongo6
    links:
      - mongo5
      - mongo6
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "iabdrs" ]

  mongo5:
    container_name: mongo5
    image: mongo
    networks:
      - mongo-network
    ports:
      - 27021:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "iabdrs" ]

  mongo6:
    container_name: mongo6
    image: mongo
    networks:
      - mongo-network
    ports:
      - 27022:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "iabdrs" ]

networks:
  mongo-network:
    driver: bridge
